dist: xenial
language: java
jdk:
- openjdk11
services:
- postgresql
before_install:
- chmod +x mvnw
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create database yourcourtdb owner postgres"
script:
- mvn clean
notifications:
  email:
    recipients:
    - juanogtir@alum.us.es
    - javvazzam@alum.us.es
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  app: dev-yourcourt-api
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: Task013